services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu_db
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    restart: unless-stopped

  client:
    image: sgu-client:latest
    build:
      context: ./client
      args:
        API_HOST: server
        API_PORT: 8080
        API_BASE: /usuarios
    container_name: sgu-client
    ports:
      - "3000:80"
    networks:
      - sgu-net
    depends_on:
      - database

  server:
    image: sgu-server:latest
    build:
      context: ./server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu_db
      DB_USER: root
      DB_PASS: root
    container_name: sgu-server
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    depends_on:
      - client

volumes:
  sgu-volume:
    external: true

networks:
  sgu-net:
    external: true